version: "2.3"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.1
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./data:/usr/share/elasticsearch/data
      - ./config:/usr/share/elasticsearch/config
      - ./logs:/usr/share/elasticsearch/logs
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    mem_limit: 2g

  kibana:
    image: docker.elastic.co/kibana/kibana:8.4.1
    ports:
      - "80:5601"
    depends_on:
      - elasticsearch
    restart: always
    mem_limit: 500M

  pyt:
    build:
      context: pyt/
    depends_on:
      - elasticsearch
    restart: always

  # mongo:
  #   image: mongo
  #   ports:
  #     - "27017:27017"
